### ISSUE TITLE
Вылет

### ISSUE THREAD

**Issue by SpeedFirePro** [Oplkill/Simple-Dota-2-Editor#1]
Когда я открываю проект программа просто закрывается с ошибкой.

**Comment by Oplkill** [comment]
Кинь из своего проекта папку npc, где все описаны герои/предметы/юниты. (не бойся, что их украдут, они и так открыты и их из "скомпилированного" архива достать не проблема.
Пробовал открыть другие проекты?
Если есть Visual Studio, то в каком участке ошибка.
Ошибка стандартная или что-то пишет информативного?

**Comment by SpeedFirePro** [comment]
Вообще ничего не пишет...
![default](https://cloud.githubusercontent.com/assets/25123815/21992054/6cb6b9bc-dc2e-11e6-8640-9295deb47d62.png)

**Comment by Oplkill** [comment]
Ну а другие проекты открываются? Пробовал удалить программу и заново скачать? Скинь проект который не открывается.(не весь, а только папку npc)(можешь на почту кинуть oplkill@gmail.com если не хочешь тут).

**Comment by Oplkill** [comment]
Ну а другие проекты открываются? Пробовал удалить программу и заново скачать? Скинь проект который не открывается.(не весь, а только папку npc)(можешь на почту кинуть oplkill@gmail.com если не хочешь тут).

**Comment by Oplkill** [comment]
Попробуй в новой версии программы, этот баг воспроизводиться?
